version: "2"
services:
  mw-requisition:
    image: openlmismw/requisition
    links:
      - db
      - log
    ports:
      - "8080"
    env_file: .env
  db:
    image: openlmis/postgres:9.6
    ports:
      - "5432"
    env_file: .env
  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/mw-requisition:/var/log'
